name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create local.properties
        working-directory: ./SelectTime/android
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Grant execute permission and build
        working-directory: ./SelectTime/android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: SelectTime/android/app/build/outputs/apk/debug/app-debug.apk